version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "yarn migrations:run:prod && yarn start:prod"
    ports:
      - "4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    env_file:
      - .env
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "5173"
    restart: unless-stopped

networks:
  default:
    name: dokploy-network
    external: true
