export type WhatsappMenuItem = {
  id: string;
  title: string;
  description?: string;
  response: string;
  /** When true, reply is generated by AI using title + response as guidance */
  aiGenerate?: boolean;
};

export const DEFAULT_WELCOME_TRIGGERS = ['hi', 'hello', 'menu', 'start', '0'];

export function normalizeMenuItems(raw: unknown): WhatsappMenuItem[] {
  if (!Array.isArray(raw)) return [];

  return raw
    .map((item, index) => {
      if (!item || typeof item !== 'object') return null;
      const row = item as Record<string, unknown>;
      const title = String(row.title ?? '').trim();
      const response = String(row.response ?? '').trim();
      const aiGenerate = row.aiGenerate === true;
      if (!title || (!response && !aiGenerate)) return null;

      const id =
        String(row.id ?? '')
          .trim()
          .slice(0, 200) ||
        title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '_')
          .replace(/^_|_$/g, '')
          .slice(0, 200) ||
        `option_${index + 1}`;

      const description = row.description
        ? String(row.description).trim().slice(0, 72)
        : undefined;

      return {
        id,
        title: title.slice(0, 24),
        ...(description ? { description } : {}),
        response: response.slice(0, 4096),
        ...(aiGenerate ? { aiGenerate: true } : {}),
      } as WhatsappMenuItem;
    })
    .filter((item): item is WhatsappMenuItem => item !== null)
    .slice(0, 10);
}
