[phases.setup]
nixPackages = ["nodejs_24", "yarn", "unzip"]

[phases.install]
cmds = [
    "export PUPPETEER_SKIP_DOWNLOAD=true && yarn install --check-cache --ignore-engines"
]

[phases.build]
cmds = [
    "export PUPPETEER_SKIP_DOWNLOAD=true && yarn run build"
]

[start]
cmd = "node dist/main.js"

[build.env]
PUPPETEER_SKIP_DOWNLOAD = "true"